package com.example.client;

public class AdditionClient {
    public static void main(String[] args) {
        // Instantiate the Service class (generated by wsimport)
        AdditionServiceService serviceService = new AdditionServiceService();

        // Get the port (interface to call remote methods)
        AdditionService port = serviceService.getAdditionServicePort();

        // Call remote method
        int a = 5;
        int b = 7;
        int result = port.add(a, b);

        System.out.println("Result of " + a + " + " + b + " = " + result);
    }
}
