package AdditionApp;


/**
* AdditionApp/AdditionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Wednesday, September 17, 2025 9:51:47 PM ICT
*/

public interface AdditionOperations 
{
  int add (int a, int b);
  void shutdown ();
} // interface AdditionOperations
