# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"%\n\x0f\x41llGradeRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\t\"!\n\x0bStatRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\t\"\'\n\x05Grade\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\"\'\n\rAllGradeReply\x12\x16\n\x06grades\x18\x01 \x03(\x0b\x32\x06.Grade\"*\n\tStatReply\x12\x0c\n\x04mean\x18\x01 \x01(\x02\x12\x0f\n\x07\x63redits\x18\x02 \x01(\x05\x32\x62\n\nStudentLMS\x12/\n\x0bGetAllGrade\x12\x10.AllGradeRequest\x1a\x0e.AllGradeReply\x12#\n\x07GetStat\x12\x0c.StatRequest\x1a\n.StatReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALLGRADEREQUEST']._serialized_start=17
  _globals['_ALLGRADEREQUEST']._serialized_end=54
  _globals['_STATREQUEST']._serialized_start=56
  _globals['_STATREQUEST']._serialized_end=89
  _globals['_GRADE']._serialized_start=91
  _globals['_GRADE']._serialized_end=130
  _globals['_ALLGRADEREPLY']._serialized_start=132
  _globals['_ALLGRADEREPLY']._serialized_end=171
  _globals['_STATREPLY']._serialized_start=173
  _globals['_STATREPLY']._serialized_end=215
  _globals['_STUDENTLMS']._serialized_start=217
  _globals['_STUDENTLMS']._serialized_end=315
# @@protoc_insertion_point(module_scope)
