# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StudentLMSStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllGrade = channel.unary_unary(
                '/StudentLMS/GetAllGrade',
                request_serializer=service__pb2.AllGradeRequest.SerializeToString,
                response_deserializer=service__pb2.AllGradeReply.FromString,
                _registered_method=True)
        self.GetStat = channel.unary_unary(
                '/StudentLMS/GetStat',
                request_serializer=service__pb2.StatRequest.SerializeToString,
                response_deserializer=service__pb2.StatReply.FromString,
                _registered_method=True)


class StudentLMSServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllGrade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StudentLMSServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllGrade': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllGrade,
                    request_deserializer=service__pb2.AllGradeRequest.FromString,
                    response_serializer=service__pb2.AllGradeReply.SerializeToString,
            ),
            'GetStat': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStat,
                    request_deserializer=service__pb2.StatRequest.FromString,
                    response_serializer=service__pb2.StatReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StudentLMS', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('StudentLMS', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StudentLMS(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllGrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StudentLMS/GetAllGrade',
            service__pb2.AllGradeRequest.SerializeToString,
            service__pb2.AllGradeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StudentLMS/GetStat',
            service__pb2.StatRequest.SerializeToString,
            service__pb2.StatReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
