
package com.example.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AdditionService", targetNamespace = "http://example.com/soap")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AdditionService {


    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://example.com/soap", className = "com.example.client.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://example.com/soap", className = "com.example.client.AddResponse")
    @Action(input = "http://example.com/soap/AdditionService/addRequest", output = "http://example.com/soap/AdditionService/addResponse")
    public int add(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

}
